# Generated by Django 4.1.3 on 2022-12-01 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Title of the blog category')),
                ('slug', models.SlugField(blank=True, help_text='This field is automatically populated', unique=True, verbose_name='Slug')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Title of the tag')),
                ('slug', models.SlugField(blank=True, help_text='This field is automatically populated', unique=True, verbose_name='Slug')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Text')),
                ('image', models.ImageField(upload_to='Blog', verbose_name='Blog image')),
                ('situation', models.BooleanField(default=False, verbose_name='Publication status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog_app.category', verbose_name='Category')),
                ('tag', models.ManyToManyField(related_name='tag', to='blog_app.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
