# Generated by Django 4.1.3 on 2022-12-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_slug_alter_blog_author_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('blog', models.ForeignKey(help_text='Comment related to which blog article', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog', verbose_name='Blog')),
                ('parent', models.ForeignKey(blank=True, help_text='If this comment is a reply to another comment, it will be completed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.comment', verbose_name='Reply to comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
