# Generated by Django 4.1.3 on 2024-01-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog_app", "0004_comment_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Blog", "verbose_name_plural": "Blogs"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=models.TextField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog",
                to="blog_app.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                help_text="Image size should be 470x570 pixels",
                upload_to="Blog",
                verbose_name="Blog Image",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="situation",
            field=models.BooleanField(default=False, verbose_name="Publication Status"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="This field is automatically populated",
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tag",
            field=models.ManyToManyField(
                related_name="tag", to="blog_app.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=30, unique=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="update",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated Date"),
        ),
        migrations.AlterField(
            model_name="category",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="This field is automatically populated",
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Category Title"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                help_text="Which article is this comment for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog_app.blog",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If this comment is a reply to another comment, it is filled in",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog_app.comment",
                verbose_name="Reply to Comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Comment Text"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="This field is automatically populated",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Tag Title"
            ),
        ),
    ]
