# Generated by Django 4.1.3 on 2024-01-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AlterModelOptions(
            name="homeslider",
            options={
                "verbose_name": "Slider Image",
                "verbose_name_plural": "Slider Images",
            },
        ),
        migrations.AlterField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                help_text="Image dimensions should be 1200x800 pixels",
                upload_to="Gallery",
                verbose_name="Gallery Image",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated Date"),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="image",
            field=models.ImageField(
                help_text="Image dimensions should be 1920x1280 pixels",
                upload_to="Slider",
                verbose_name="Slider Image",
            ),
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated Date"),
        ),
    ]
