# Generated by Django 4.1.3 on 2024-01-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("food_app", "0006_alter_comment_food_alter_food_descripion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="food",
            options={"verbose_name": "Food", "verbose_name_plural": "Foods"},
        ),
        migrations.RemoveField(
            model_name="food",
            name="descripion",
        ),
        migrations.RemoveField(
            model_name="food",
            name="situation",
        ),
        migrations.AddField(
            model_name="food",
            name="availability",
            field=models.BooleanField(default=True, verbose_name="Availability"),
        ),
        migrations.AddField(
            model_name="food",
            name="description",
            field=models.TextField(
                default="No description provided.", verbose_name="Food Description"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="food",
            field=models.ForeignKey(
                help_text="Which food is this comment about",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="food_app.food",
                verbose_name="Food",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Name and Surname"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If this comment is a reply to another comment, it will be filled",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="food_app.comment",
                verbose_name="Reply to Comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Comment Text"),
        ),
        migrations.AlterField(
            model_name="food",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="food",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("drinks", "Beverage"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                max_length=20,
                verbose_name="Food Type",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="image",
            field=models.ImageField(
                help_text="Images should be in the size of 800x480 pixels",
                upload_to="Foods",
                verbose_name="Food Image",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Food Name"),
        ),
        migrations.AlterField(
            model_name="food",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Food Price"),
        ),
        migrations.AlterField(
            model_name="food",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="This field is automatically populated",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="status",
            field=models.BooleanField(
                default=False,
                help_text="Publication status on the website",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated Date"),
        ),
    ]
