# Generated by Django 4.1.3 on 2024-01-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_app", "0004_alter_reservation_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(verbose_name="Reservation Date"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="number",
            field=models.PositiveSmallIntegerField(verbose_name="Number of Guests"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(verbose_name="Reservation Time"),
        ),
    ]
